language: java 
install: mvn install clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
script: mvn verify

jdk:
  - oraclejdk7

branches:
  only:
    - master

notifications:
    email: false

